markdown: rdiscount
auto: true

url: .

owner-name: Florian Holzner
owner-page: http://lebobs.ch/
owner-email: bobschi@lavabit.com

license: <a rel="license" href="http://creativecommons.org/licenses/by-nc/3.0/at/"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc/3.0/at/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/3.0/at/">Creative Commons Attribution-NonCommercial 3.0 Austria License</a> by